import { createRng, pools, type Rng } from "./rng";

/** Generated by `zengin mock` from the Page schema. Seed 7731; the same data on every run. */
export interface Page {
  id: string;
  author: string;
  updated: string;
  views: number;
}

export function makePage(index: number, rng: Rng): Page {
  const first = rng.pick(pools.firstNames);
  const last = rng.pick(pools.lastNames);
  return {
    id: rng.id("DOC", index),
    author: `${first} ${last}`,
    updated: rng.date(90, 0),
    views: rng.int(40, 6000),
  };
}

export const pages: Page[] = Array.from({ length: 10 }, (_, i) => makePage(i, createRng(7731 * 7919 + i)));
