import { fieldType, PRESETS, resolveField, type EntitySchema, type FieldSpec, type MockSchema } from "./schema.js";
import { RUNTIME_SOURCE } from "./runtime.js";

export interface GenerateOptions {
  /** Directory the modules go in, relative to the project. Default `src/mock`. */
  dir?: string;
  /** Overrides every entity's count. */
  count?: number;
}

/** Files to write, keyed by project-relative path: the runtime once, one module per entity. */
export function generateMock(schema: MockSchema, opts: GenerateOptions = {}): Record<string, string> {
  const dir = opts.dir ?? "src/mock";
  const seed = schema.seed ?? 7;
  const out: Record<string, string> = { [`${dir}/rng.ts`]: RUNTIME_SOURCE };
  const known = new Set(schema.entities.map((e) => pluralOf(e.name)));
  for (const entity of schema.entities) {
    for (const [field, spec] of Object.entries(entity.fields)) {
      const f = resolveField(spec);
      if (f.type === "ref" && !known.has(f.entity ?? "")) throw new Error(`${entity.name}.${field} refers to "${f.entity}", which is not an entity in this schema (${[...known].join(", ")}).`);
    }
    out[`${dir}/${pluralOf(entity.name)}.ts`] = renderEntity(entity, seed, opts.count);
  }
  return out;
}

/** Presets by name into a schema; unknown names fail with the list. */
export function schemaFromPresets(names: string[], opts: { seed?: number; count?: number } = {}): MockSchema {
  const unknown = names.filter((n) => !(n in PRESETS));
  if (unknown.length) throw new Error(`No preset named ${unknown.map((n) => `"${n}"`).join(", ")}. Presets: ${Object.keys(PRESETS).join(", ")}.`);
  return { seed: opts.seed, entities: names.map((n) => ({ ...PRESETS[n]!, count: opts.count ?? PRESETS[n]!.count })) };
}

function renderEntity(entity: EntitySchema, seed: number, countOverride: number | undefined): string {
  const plural = pluralOf(entity.name);
  const count = countOverride ?? entity.count ?? 20;
  const needsName = Object.values(entity.fields).some((s) => ["email", "fullName", "firstName", "lastName"].includes(resolveField(s).type));
  const needsCompany = Object.values(entity.fields).some((s) => ["email", "url", "company"].includes(resolveField(s).type));
  const refs = [...new Set(Object.values(entity.fields).map(resolveField).filter((f) => f.type === "ref").map((f) => f.entity ?? ""))];
  const typeLines = Object.entries(entity.fields).map(([name, spec]) => `  ${name}: ${fieldType(spec)};`);
  const valueLines = Object.entries(entity.fields).map(([name, spec]) => `    ${name}: ${expression(spec, name)},`);
  const imports = [`import { createRng, email, phone, pools, url, type Rng } from "./rng";`, ...refs.map((r) => `import { ${r} } from "./${r}";`)];

  return `${imports.join("\n")}

/** Generated by \`zengin mock\` from the ${entity.name} schema. Seed ${seed}; the same data on every run. */
export interface ${entity.name} {
${typeLines.join("\n")}
}

export function make${entity.name}(index: number, rng: Rng): ${entity.name} {
${needsName ? `  const first = rng.pick(pools.firstNames);\n  const last = rng.pick(pools.lastNames);\n` : ""}${needsCompany ? `  const company = rng.pick(pools.companies);\n` : ""}  return {
${valueLines.join("\n")}
  };
}

export const ${plural}: ${entity.name}[] = Array.from({ length: ${count} }, (_, i) => make${entity.name}(i, createRng(${seed} * 7919 + i)));
`;
}

/** The runtime expression for one field. */
function expression(spec: FieldSpec, name: string): string {
  const f = resolveField(spec);
  switch (f.type) {
    case "id":
      return `rng.id(${JSON.stringify(f.prefix ?? name.toUpperCase().slice(0, 3))}, index)`;
    case "firstName":
      return "first";
    case "lastName":
      return "last";
    case "fullName":
      return "`${first} ${last}`";
    case "email":
      return "email(first, last, company, rng)";
    case "company":
      return "company";
    case "jobTitle":
      return "rng.pick(pools.jobTitles)";
    case "city":
      return "rng.pick(pools.cities)";
    case "country":
      return "rng.pick(pools.countries)";
    case "sentence":
      return "rng.sentence()";
    case "paragraph":
      return "rng.paragraph()";
    case "words":
      return `rng.words(${f.min ?? 2}, ${f.max ?? 4})`;
    case "url":
      return "url(company, rng)";
    case "phone":
      return "phone(rng)";
    case "boolean":
      return `rng.bool(${f.p ?? 0.5})`;
    case "date":
      return `rng.date(${f.pastDays ?? 365}, ${f.futureDays ?? 0})`;
    case "money":
      return `rng.int(${f.min ?? 0}, ${f.max ?? 1000})`;
    case "int":
      return `rng.int(${f.min ?? 0}, ${f.max ?? 100})`;
    case "float":
      return `rng.float(${f.min ?? 0}, ${f.max ?? 1}, ${f.digits ?? 2})`;
    case "percent":
      return `rng.float(${f.min ?? 0}, ${f.max ?? 100}, 1)`;
    case "enum":
      return `rng.pick(${JSON.stringify(f.values ?? [])} as const${f.weights ? `, ${JSON.stringify(f.weights)}` : ""})`;
    case "series":
      return `rng.series(${f.length ?? 12}, ${f.min ?? 0}, ${f.max ?? 100}, ${JSON.stringify(f.trend ?? "flat")})`;
    case "ref":
      return `rng.pick(${f.entity ?? "rows"}).id`;
  }
}

/** `User` to `users`, `Company` to `companies`, `Address` to `addresses`. */
export function pluralOf(name: string): string {
  const lower = name.charAt(0).toLowerCase() + name.slice(1);
  if (/[^aeiou]y$/.test(lower)) return `${lower.slice(0, -1)}ies`;
  if (/(s|x|z|ch|sh)$/.test(lower)) return `${lower}es`;
  return `${lower}s`;
}
