import { createRng, email, pools, type Rng } from "./rng";

/** Generated by `zengin mock` from the Customer schema. Seed 20260912; the same data on every run. */
export interface Customer {
  id: string;
  name: string;
  company: string;
  email: string;
  plan: "Free" | "Starter" | "Team" | "Business" | "Enterprise";
  status: "active" | "trial" | "past-due" | "churned";
  seats: number;
  usage: number[];
  since: string;
}

export function makeCustomer(index: number, rng: Rng): Customer {
  const first = rng.pick(pools.firstNames);
  const last = rng.pick(pools.lastNames);
  const company = rng.pick(pools.companies);
  return {
    id: rng.id("CUS", index),
    name: `${first} ${last}`,
    company: company,
    email: email(first, last, company, rng),
    plan: rng.pick(["Free","Starter","Team","Business","Enterprise"] as const, [4,3,3,2,1]),
    status: rng.pick(["active","trial","past-due","churned"] as const, [6,2,1,1]),
    seats: rng.int(1, 60),
    usage: rng.series(12, 10, 90, "up"),
    since: rng.date(700, 0),
  };
}

export const customers: Customer[] = Array.from({ length: 40 }, (_, i) => makeCustomer(i, createRng(20260912 * 7919 + i)));
