import { createRng, type Rng } from "./rng";
import { customers } from "./customers";

/** Generated by `zengin mock` from the Event schema. Seed 20260912; the same data on every run. */
export interface Event {
  id: string;
  customer: string;
  kind: "signup" | "upgrade" | "invoice" | "support" | "churn";
  at: string;
}

export function makeEvent(index: number, rng: Rng): Event {
  return {
    id: rng.id("EVT", index),
    customer: rng.pick(customers).id,
    kind: rng.pick(["signup","upgrade","invoice","support","churn"] as const, [4,2,3,2,1]),
    at: rng.date(3, 0),
  };
}

export const events: Event[] = Array.from({ length: 8 }, (_, i) => makeEvent(i, createRng(20260912 * 7919 + i)));
