import { createRng, type Rng } from "./rng";

/** Generated by `zengin mock` from the Invoice schema. Seed 20260912; the same data on every run. */
export interface Invoice {
  id: string;
  amount: number;
  status: "paid" | "open" | "failed";
  issued: string;
}

export function makeInvoice(index: number, rng: Rng): Invoice {
  return {
    id: rng.id("INV", index),
    amount: rng.int(299, 349),
    status: rng.pick(["paid","open","failed"] as const, [7,1,1]),
    issued: rng.date(180, 0),
  };
}

export const invoices: Invoice[] = Array.from({ length: 6 }, (_, i) => makeInvoice(i, createRng(20260912 * 7919 + i)));
