import { createRng, type Rng } from "./rng";

/** Generated by `zengin mock` from the Metric schema. Seed 20260912; the same data on every run. */
export interface Metric {
  id: string;
  revenue: number[];
  refunds: number[];
  activeUsers: number[];
  conversionBps: number[];
  churnBps: number[];
}

export function makeMetric(index: number, rng: Rng): Metric {
  return {
    id: rng.id("MET", index),
    revenue: rng.series(30, 18000, 27000, "up"),
    refunds: rng.series(30, 400, 1300, "flat"),
    activeUsers: rng.series(30, 2800, 3500, "up"),
    conversionBps: rng.series(30, 260, 380, "flat"),
    churnBps: rng.series(30, 130, 220, "down"),
  };
}

export const metrics: Metric[] = Array.from({ length: 1 }, (_, i) => makeMetric(i, createRng(20260912 * 7919 + i)));
