import { createRng, type Rng } from "./rng";

/** Generated by `zengin mock` from the Signup schema. Seed 20260912; the same data on every run. */
export interface Signup {
  id: string;
  plan: "Free" | "Starter" | "Team" | "Business" | "Enterprise";
  at: string;
}

export function makeSignup(index: number, rng: Rng): Signup {
  return {
    id: rng.id("SGN", index),
    plan: rng.pick(["Free","Starter","Team","Business","Enterprise"] as const, [10,5,3,1,0.2]),
    at: rng.date(60, 0),
  };
}

export const signups: Signup[] = Array.from({ length: 400 }, (_, i) => makeSignup(i, createRng(20260912 * 7919 + i)));
