import { createRng, type Rng } from "./rng";

/** Generated by `zengin mock` from the Thread schema. Seed 9012; the same data on every run. */
export interface Thread {
  id: string;
  at: string;
  turns: number;
}

export function makeThread(index: number, rng: Rng): Thread {
  return {
    id: rng.id("THR", index),
    at: rng.date(12, 0),
    turns: rng.int(2, 14),
  };
}

export const threads: Thread[] = Array.from({ length: 6 }, (_, i) => makeThread(i, createRng(9012 * 7919 + i)));
