import { createRng, type Rng } from "./rng";

/** Generated by `zengin mock` from the Listing schema. Seed 1204; the same data on every run. */
export interface Listing {
  id: string;
  stock: number;
  rating: number;
  reviews: number;
  sale: boolean;
}

export function makeListing(index: number, rng: Rng): Listing {
  return {
    id: rng.id("SKU", index),
    stock: rng.int(0, 120),
    rating: rng.float(3.6, 5, 1),
    reviews: rng.int(3, 900),
    sale: rng.bool(0.3),
  };
}

export const listings: Listing[] = Array.from({ length: 12 }, (_, i) => makeListing(i, createRng(1204 * 7919 + i)));
