/*
 * Writes src/generated/versions.ts: the version a created project pins for each Zengin package it
 * depends on, read from the workspace at build time.
 *
 * It is generated rather than written down because the written-down version was wrong within two days.
 * A single `^0.1.0` covered the cli, the hook and the MCP server, so a project scaffolded after four
 * releases still installed the first one: `zengin define`, `profiles:` and `add --install` were all
 * documented and all missing from the project that was handed over. Changesets bumps these package.json
 * files in the version PR and the build runs after that, so whatever is published is what gets pinned.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const PACKAGES = ["cli", "hook", "mcp"];

const versions = {};
for (const name of PACKAGES) {
  const pkg = JSON.parse(readFileSync(join(here, "..", "..", name, "package.json"), "utf8"));
  versions[pkg.name] = `^${pkg.version}`;
}

const out = join(here, "..", "src", "generated", "versions.ts");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/versions.mjs from the workspace. Do not edit: every build overwrites it.\n` +
    `export const ZENGIN_VERSIONS: Readonly<Record<string, string>> = ${JSON.stringify(versions, null, 2)};\n`,
);
