import { createRng, pools, type Rng } from "./rng";

/** Generated by `zengin mock` from the Review schema. Seed 2041; the same data on every run. */
export interface Review {
  id: string;
  author: string;
  status: "pending" | "approved" | "rejected" | "changes";
  submitted: string;
}

export function makeReview(index: number, rng: Rng): Review {
  const first = rng.pick(pools.firstNames);
  const last = rng.pick(pools.lastNames);
  return {
    id: rng.id("ZN", index),
    author: `${first} ${last}`,
    status: rng.pick(["pending","approved","rejected","changes"] as const, [5,2,1,2]),
    submitted: rng.date(6, 0),
  };
}

export const reviews: Review[] = Array.from({ length: 8 }, (_, i) => makeReview(i, createRng(2041 * 7919 + i)));
