/** Seeded random data for the mock modules. Generated by `zengin mock`; edit the pools freely. */

export interface Rng {
  next(): number;
  int(min: number, max: number): number;
  float(min: number, max: number, digits?: number): number;
  bool(p?: number): boolean;
  pick<T>(items: readonly T[], weights?: readonly number[]): T;
  id(prefix: string, index: number): string;
  date(pastDays?: number, futureDays?: number): string;
  series(length: number, min: number, max: number, trend?: "up" | "down" | "flat"): number[];
  words(min: number, max: number): string;
  sentence(): string;
  paragraph(): string;
}

/** mulberry32: small, fast, and the same sequence for the same seed on every platform. */
export function createRng(seed: number): Rng {
  let a = seed >>> 0;
  const next = (): number => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const rng: Rng = {
    next,
    int: (min, max) => min + Math.floor(next() * (max - min + 1)),
    float: (min, max, digits = 2) => Number((min + next() * (max - min)).toFixed(digits)),
    bool: (p = 0.5) => next() < p,
    pick: (items, weights) => {
      if (!weights) return items[Math.floor(next() * items.length)]!;
      const total = weights.reduce((s, w) => s + w, 0);
      let r = next() * total;
      for (let i = 0; i < items.length; i++) {
        r -= weights[i] ?? 0;
        if (r <= 0) return items[i]!;
      }
      return items[items.length - 1]!;
    },
    id: (prefix, index) => `${prefix}-${String(1000 + index)}`,
    date: (pastDays = 365, futureDays = 0) => {
      const span = pastDays + futureDays;
      const offset = -pastDays + next() * span;
      const d = new Date(EPOCH + offset * 86400000);
      return d.toISOString().slice(0, 10);
    },
    series: (length, min, max, trend = "flat") => {
      const out: number[] = [];
      const step = trend === "up" ? (max - min) / (length * 2) : trend === "down" ? -(max - min) / (length * 2) : 0;
      let v = trend === "up" ? min + (max - min) * 0.3 : trend === "down" ? max - (max - min) * 0.3 : (min + max) / 2;
      for (let i = 0; i < length; i++) {
        v = Math.min(max, Math.max(min, v + step + (next() - 0.5) * (max - min) * 0.2));
        out.push(Math.round(v));
      }
      return out;
    },
    words: (min, max) => {
      const n = rng.int(min, max);
      const out: string[] = [];
      for (let i = 0; i < n; i++) out.push(rng.pick(pools.words));
      return out.join(" ").replace(/^./, (c) => c.toUpperCase());
    },
    sentence: () => rng.words(6, 12) + ".",
    paragraph: () => [rng.sentence(), rng.sentence(), rng.sentence()].join(" "),
  };
  return rng;
}

/** A fixed "now", so dates are stable across runs and screenshots: 2026-09-12. */
export const EPOCH = Date.UTC(2026, 8, 12);

export const pools = {
  firstNames: ["Ada", "Grace", "Linus", "Mina", "Jonas", "Priya", "Tomás", "Yuki", "Farah", "Noah", "Ines", "Kwame", "Sofia", "Emil", "Leila", "Marcus", "Hana", "Diego", "Aisha", "Olu", "Petra", "Ravi", "Zoe", "Bram", "Nadia", "Theo", "Amara", "Felix"],
  lastNames: ["Okafor", "Lindqvist", "Raman", "Brewster", "Sato", "Haddad", "Mendes", "Novak", "Achebe", "Costa", "Weber", "Ivanova", "Delacroix", "Osei", "Nakamura", "Fischer", "Rossi", "Kaur", "Berg", "Moreau", "Silva", "Andersen", "Tanaka", "Dubois", "Quinn", "Park", "Nguyen", "Adler"],
  companies: ["Northwind", "Lumen Labs", "Halyard", "Tessel", "Quarry", "Brightline", "Ferro", "Oakline", "Meridian", "Pipeworks", "Sable", "Kestrel", "Ridgeway", "Alder", "Vantage", "Cobalt Works", "Harbor", "Slate", "Fathom", "Juniper", "Beacon", "Marlow", "Cinder", "Trellis"],
  jobTitles: ["Design lead", "Frontend engineer", "Product manager", "Founder", "Design systems engineer", "Head of platform", "Staff engineer", "UX researcher", "Engineering manager", "Developer advocate"],
  cities: ["Berlin", "Lisbon", "Toronto", "Austin", "Copenhagen", "Singapore", "Melbourne", "Amsterdam", "Nairobi", "São Paulo", "Tokyo", "Dublin"],
  countries: ["Germany", "Portugal", "Canada", "United States", "Denmark", "Singapore", "Australia", "Netherlands", "Kenya", "Brazil", "Japan", "Ireland"],
  words: ["token", "system", "review", "signal", "module", "release", "queue", "surface", "contract", "rule", "theme", "brand", "engine", "preview", "template", "check", "drift", "fix", "scope", "layer", "grid", "field", "panel", "report", "digest", "quota", "seat", "invoice", "plan", "usage"],
  tlds: ["com", "io", "dev", "co"],
};

export function email(first: string, last: string, company: string, rng: Rng): string {
  const clean = (s: string) => s.normalize("NFD").replace(/[^a-zA-Z]/g, "").toLowerCase();
  return `${clean(first)}${rng.bool(0.3) ? "." + clean(last).charAt(0) : ""}@${clean(company)}.${rng.pick(pools.tlds)}`;
}

export function phone(rng: Rng): string {
  return `+1 ${rng.int(200, 989)} ${rng.int(200, 999)} ${String(rng.int(0, 9999)).padStart(4, "0")}`;
}

export function url(company: string, rng: Rng): string {
  return `https://${company.normalize("NFD").replace(/[^a-zA-Z]/g, "").toLowerCase()}.${rng.pick(pools.tlds)}`;
}
