import { createRng, email, pools, type Rng } from "./rng";

/** Generated by `zengin mock` from the Account schema. Seed 4401; the same data on every run. */
export interface Account {
  id: string;
  name: string;
  email: string;
  role: "owner" | "admin" | "member";
  joined: string;
}

export function makeAccount(index: number, rng: Rng): Account {
  const first = rng.pick(pools.firstNames);
  const last = rng.pick(pools.lastNames);
  const company = rng.pick(pools.companies);
  return {
    id: rng.id("USR", index),
    name: `${first} ${last}`,
    email: email(first, last, company, rng),
    role: rng.pick(["owner","admin","member"] as const, [1,2,6]),
    joined: rng.date(400, 0),
  };
}

export const accounts: Account[] = Array.from({ length: 12 }, (_, i) => makeAccount(i, createRng(4401 * 7919 + i)));
